apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::051826708837:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-OaHgbBFEaxGp
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::051826708837:user/raju
      username: raju
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::051826708837:user/ramesh
      username: ramesh
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::051826708837:user/john
      username: john
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::051826708837:user/paul
      username: paul
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-26T06:58:53Z"
  name: aws-auth
  namespace: kube-system
  uid: 3f599d6a-5c92-46e2-9c8b-a2b9a6eb1e95