apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::051826708837:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-sQ8UaSWTixX0
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::051826708837:user/raju
      username: raju
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::051826708837:user/ramesh
      username: ramesh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-09-25T05:30:17Z"
  name: aws-auth
  namespace: kube-system
  uid: be9e4c51-9674-45f7-affb-deae7d162862